# Generated by Django 3.2.9 on 2021-11-04 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_id', models.IntegerField()),
                ('src', models.ImageField(upload_to='images/%Y/%m/%d/')),
                ('entity_type', models.IntegerField()),
            ],
        ),
    ]
